### PR TITLE
Support new Cordova build folder structure

### PR DESCRIPTION
**Pull request by ofalvai**
### Checklist

- [ ] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [ ] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context

Similar to the change in the Cordova Archive step: https://github.com/bitrise-steplib/steps-cordova-archive/pull/56

### Changes

- Handle new path structure
- Replace old sample app as it suffered from a lot of issues and didn't work when building against the latest iOS SDKs

### CODE REVIEW

**Comment by QuentinFarizon** [comment]
Hello @ofalvai any news on this ?

**Comment by QuentinFarizon** [comment]
@ofalvai Can this move forward ? It's just missing a merge no ?

**Comment by QuentinFarizon** [comment]
@ofalvai :pray:

**Review by lpusok — DISMISSED** [review]

**Review by lpusok — APPROVED** [review]

**Comment by ofalvai** [comment]
Thank you for the patience everyone! We had to pause this for other priorities and some internal testing issues (not visible in this PR), but the PR is now merged and released in [version 2.3.2](https://github.com/bitrise-steplib/steps-ionic-archive/releases/tag/2.3.2)

**Pull request merged**
