### PR TITLE
specify ionic & cordova versions

### PR DESCRIPTION
**Pull request by godrei**

### CODE REVIEW

**Comment by godrei** [comment]
@patrickbussmann i will merge this PR since @trapacska reviewed it. Let me know if have any note/issue to the PR.

**Comment by patrickbussmann** [comment]
Looks okay. I tested the whole steps-ionic-archive on our test projects.

- steps-ionic - Ionic Conference App - Android
- steps-ionic - Ionic Conference App - iOS

And I got some errors.

Currently it's:

	Building project
	$ ionic "cordova" "--no-interactive" "build" "--release" "--device" "android"
	? What platform would you like to build: ios, android: 

So I think there are some bugs in it.
Maybe you can check that you build the conference app via this workflow I specified on Bitrise.io because then this is a complete workflow which is useful for later project scanner :+1: 

I want that building Ionic apps is as easy as fill out some configuration things :sunglasses:

**Comment by godrei** [comment]
Hi @patrickbussmann could you please share the bitrise.yml you used for the failed build?

**Comment by godrei** [comment]
The easiest way to test the step:

- clone the step repo
- cd into the step dir
- set `SAMPLE_APP_URL` (i tested with https://github.com/driftyco/ionic-conference-app.git and https://github.com/bitrise-samples/ionic-2)
- configure the step inputs in the `test` workflow / `path::./:` step
  - you can check the available input keys in the step.yml 
- call `bitrise run test`

The `test` workflow will cd into a _tmp dir, clone the desired sample app and run the step.

**Comment by patrickbussmann** [comment]
@godrei your test is the basic test. I think its better to have an real test scenario :+1: 

https://www.bitrise.io/app/976442eba93cd58f#/builds (you should have access to it because you're member of the organization)

	---
	format_version: 1.3.1
	default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
	app:
	  envs:
	  - BITRISE_SCHEME: Ionic Conference
		opts:
		  is_expand: true
	workflows:
	  _ci_finish:
		steps:
		- deploy-to-bitrise-io:
			run_if: '{{getenv "BITRISE_BUILD_URL" | ne ""}}'
	  _ci_setup:
		steps:
		- activate-ssh-key:
			run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
		- git-clone: {}
	  ci-android:
		before_run:
		- _ci_setup
		after_run:
		- build-android
		- _ci_finish
		steps: 
	  build-android:
		steps:
		- npm:
			inputs:
			- command: install
		- npm:
			inputs:
			- command: install @ionic/cli-plugin-ionic-angular@latest @ionic/cli-plugin-cordova@latest
				ionic@3 cordova@7
		- git&amp;#x;
			title: Ionic Archive
			inputs:
			- platform: android
		before_run: 
		after_run: 
	  deploy-android:
		before_run:
		- _ci_setup
		- build-android
		after_run:
		- _ci_finish
		steps:
		- google-play-deploy@1.1.0:
			inputs:
			- service_account_json_key_path: https://.../a123bcd4e5f6.json
			- package_name: io.ionic.conferenceapp
			- apk_path: "$BITRISE_APK_PATH"
			- track: beta
			- whatsnews_dir: ''
			- service_account_email: ''
			- key_file_path: ''
	trigger_map:
	- tag: "*"
	  workflow: deploy-android
	- push_branch: master
	  workflow: ci-android

**And error log.**

	Building project
	$ ionic "cordova" "--no-interactive" "build" "--release" "--device" "android"
	? What platform would you like to build: ios, android: 

I test it the whole time and thought its a problem with the ionic version or cordova version. But then I changed it and its not working, too.

Maybe you find a solution :+1:

**Comment by patrickbussmann** [comment]
@godrei: @trapacska:

I checked the log file of your `steps-ionic-archive` project on Bitrise.io.
It contains much more problems as I have :laughing: 

2017-05-25 18_20_18-steps-ionic-archive - build 10 ac86447b86a133f4 - bitrise

And thats the same for all your commands.

    $ ionic "cordova" "--no-interactive" "platform" "add" "ios"
    cordova is not a valid task

So yes, the test is green and running - but the result is no IPA nor APK :smile: 
The result is, that it's not working :-(

**Comment by viktorbenei** [comment]
good catch @patrickbussmann !!

@godrei please check/review this, and change the tests to fail if there's no generated ipa or apk

**Pull request merged**
